In [1]:
from src.MOF_builder.v2_builder import net_optimizer
from src.MOF_builder.v2_builder import extract_type_atoms_fcoords_in_primitive_cell,extract_unit_cell,make_supercell_3x3x3
import time
import numpy as np

start_time = time.time()
node_cif = 'node1.cif'
linker_cif = 'diedge.cif'
node_target_type = 'Zr'
#template cif 
template_cif = 'fcu.cif'
template_cell_info,_,vvnode = extract_type_atoms_fcoords_in_primitive_cell(template_cif, 'V')
_,_,eenode = extract_type_atoms_fcoords_in_primitive_cell(template_cif, 'E')
unit_cell = extract_unit_cell(template_cell_info)

vvnode = np.unique(np.array(vvnode,dtype=float),axis=0)
eenode = np.unique(np.array(eenode,dtype=float),axis=0)
##loop over super333xxnode and super333yynode to find the pair of x node in unicell which pass through the yynode
vvnode333 = make_supercell_3x3x3(vvnode)
eenode333 = make_supercell_3x3x3(eenode)
fcu = net_optimizer()
fcu.analyze_template_ditopic(vvnode333,eenode333,unit_cell,template_cell_info)
fcu.node_info(node_cif,node_target_type)
fcu.linker_info(linker_cif)
fcu.set_maxfun(10000)
fcu.set_opt_method('L-BFGS-B')
fcu.optimize()
print("--- %s seconds ---" % (time.time() - start_time))
fcu.place_edge_in_net()
supercell = [0,0,0]
fcu.set_supercell(supercell)
fcu.make_supercell_ditopic()
fcu.set_virtual_edge(False)
all_eG = fcu.make_eG_ditopic()
eG = fcu.main_frag_eG()
fcu.set_node_topic(12)
unsaturated_node = fcu.find_unsaturated_node_eG()
sc_unit_cell = fcu.sc_unit_cell
fcu.set_node_terminamtion('methyl.pdb')
fcu.add_terminations_to_unsaturated_node()
print("--- %s seconds ---" % (time.time() - start_time))
unsaturated_node_xoo_dict = fcu.unsaturated_vnode_xoo_dict


 no symmetry operation
 no symmetry operation
P1 cell
P1 cell
node_x_fcoords[[ 0.155 -0.105 -0.104]
 [-0.155  0.095 -0.113]
 [ 0.155  0.095 -0.113]
 [-0.155 -0.105 -0.104]
 [-0.155 -0.095  0.113]
 [ 0.155  0.105  0.104]
 [-0.155  0.105  0.104]
 [ 0.155 -0.095  0.113]]
node_ccoords_com[ 0.00191613  0.00388065 -0.00972903]
P1 cell
P1 cell
node_x_fcoords[[ 0.0185 -0.1565 -0.0045]
 [-0.0185  0.1565  0.0045]]
node_ccoords_com[-0.09490217 -0.03018043  0.21753696]
RUNNING THE L-BFGS-B CODE

           * * *

Machine precision = 2.220D-16
 N =          252     M =           10

At X0         0 variables are exactly at the bounds

At iterate    0    f=  3.42197D+06    |proj g|=  3.38526D+03


 This problem is unconstrained.



At iterate    1    f=  3.42019D+06    |proj g|=  2.11988D+03

At iterate    2    f=  3.41918D+06    |proj g|=  1.59480D+03

At iterate    3    f=  3.41815D+06    |proj g|=  3.27332D+03

At iterate    4    f=  3.41787D+06    |proj g|=  2.39960D+03

At iterate    5    f=  3.41756D+06    |proj g|=  2.90386D+02

At iterate    6    f=  3.41752D+06    |proj g|=  2.63099D+02

At iterate    7    f=  3.41742D+06    |proj g|=  2.54670D+02

At iterate    8    f=  3.41741D+06    |proj g|=  2.62540D+02

At iterate    9    f=  3.41741D+06    |proj g|=  1.15391D+02

At iterate   10    f=  3.41741D+06    |proj g|=  5.26663D+01

At iterate   11    f=  3.41740D+06    |proj g|=  7.44592D+01

At iterate   12    f=  3.41740D+06    |proj g|=  6.90576D+01

At iterate   13    f=  3.41740D+06    |proj g|=  1.84402D+01

At iterate   14    f=  3.41740D+06    |proj g|=  1.44821D+01

At iterate   15    f=  3.41740D+06    |proj g|=  1.92318D+01

At iterate   16    f=  3.41740D+06    |proj g|=  5.57862D+01

At iter

In [2]:
#from src.MOF_builder.v2_builder import temp_save_eG_TERM_gro
#supercell = [1,1,1]
#fcu.set_supercell(supercell)
#fcu.make_supercell_ditopic()
#all_eG = fcu.make_eG_ditopic()
#eG = fcu.main_frag_eG()
#fcu.set_node_topic(12)
#unsaturated_node = fcu.find_unsaturated_node_eG()
#sc_unit_cell = fcu.sc_unit_cell
#fcu.set_node_terminamtion('methyl.pdb')
#fcu.add_terminations_to_unsaturated_node()
#temp_save_eG_TERM_gro(eG,sc_unit_cell,unsaturated_node_xoo_dict)

In [3]:
from src.MOF_builder.v2_builder import temp_save_eG_TERM_gro
#find unsaturated node idx
unsaturated_node_idx = []
for node in unsaturated_node:
    unsaturated_node_idx.append(fcu.eG.nodes[node]['index'])
fcu.set_remove_node_list(unsaturated_node_idx)
fcu.make_eG_ditopic()
eG = fcu.main_frag_eG()
fcu.set_node_topic(12)
unsaturated_node = fcu.find_unsaturated_node_eG()
sc_unit_cell = fcu.sc_unit_cell
fcu.set_node_terminamtion('methyl.pdb')
fcu.add_terminations_to_unsaturated_node()
temp_save_eG_TERM_gro(eG,sc_unit_cell, fcu.unsaturated_vnode_xoo_dict)



no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V1_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V1_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V1_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V1_[0. 0. 0.]
no xoo for edge node, this l

In [53]:
fcu.set_remove_node_list([])
fcu.place_edge_in_net()
supercell = [2,2,1]
fcu.set_supercell(supercell)
fcu.make_supercell_ditopic()
all_eG = fcu.make_eG_ditopic()

eG = fcu.main_frag_eG()
fcu.set_node_topic(12)
unsaturated_node = fcu.find_unsaturated_node_eG()
sc_unit_cell = fcu.sc_unit_cell
fcu.set_node_terminamtion('methyl.pdb')
fcu.add_terminations_to_unsaturated_node()
temp_save_eG_TERM_gro(eG,sc_unit_cell, fcu.unsaturated_vnode_xoo_dict)

no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V0_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V1_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V1_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V1_[0. 0. 0.]
no xoo for edge node, this linker is a dangling unsaturated linker V1_[0. 0. 0.]
no xoo for edge node, this l

In [54]:
from src.MOF_builder.v2_builder import pname
from src.MOF_builder.makesuperG import  lname
from src.MOF_builder._supercell import Carte_points_generator
import networkx as nx
carte_supercell = Carte_points_generator(fcu.supercell)

supercell_x = fcu.supercell[0]+1
supercell_y = fcu.supercell[1]+1
supercell_z = fcu.supercell[2]+1
print('carte_supercell',carte_supercell[0])
outnodes = []
for n in eG.nodes():
    if pname(n) !='EDGE':
        #make lname(n) as int, compare with the cart_supercell list
        lname_n = lname(n).tolist()
        if lname_n[0] not in range(supercell_x) or lname_n[1] not in range(supercell_y) or lname_n[2] not in range(supercell_z):
            print('node',n,'is not in supercell')
            outnodes.append(n)
        else:
            print('node',n,'is in supercell')

for n in outnodes:
    for e in list(eG.edges(n)):
        eG.remove_edge(e[0],e[1])
        if pname(e[0]) == 'EDGE':
            print('remove edge',e[0])
            eG.remove_node(e[0])
        if pname(e[1]) == 'EDGE':
            print('remove edge',e[0])
            eG.remove_node(e[1])
        
    eG.remove_node(n)
main_eG = [eG.subgraph(c).copy() for c in nx.connected_components(eG)][0]

temp_save_eG_TERM_gro(main_eG,sc_unit_cell, {})
            


            


carte_supercell [0. 0. 0.]
node V0_[0. 0. 0.] is in supercell
node V1_[0. 0. 0.] is in supercell
node V2_[0. 0. 0.] is in supercell
node V3_[0. 0. 0.] is in supercell
node V2_[-1.  0.  0.] is not in supercell
node V3_[-1.  0.  0.] is not in supercell
node V1_[ 0. -1.  0.] is not in supercell
node V3_[ 0. -1.  0.] is not in supercell
node V3_[-1. -1.  0.] is not in supercell
node V1_[ 0.  0. -1.] is not in supercell
node V2_[ 0.  0. -1.] is not in supercell
node V2_[-1.  0. -1.] is not in supercell
node V1_[ 0. -1. -1.] is not in supercell
node V0_[1. 0. 0.] is in supercell
node V1_[1. 0. 0.] is in supercell
node V2_[1. 0. 0.] is in supercell
node V3_[1. 0. 0.] is in supercell
node V1_[ 1. -1.  0.] is not in supercell
node V3_[ 1. -1.  0.] is not in supercell
node V1_[ 1.  0. -1.] is not in supercell
node V2_[ 1.  0. -1.] is not in supercell
node V1_[ 1. -1. -1.] is not in supercell
node V0_[0. 1. 0.] is in supercell
node V1_[0. 1. 0.] is in supercell
node V2_[0. 1. 0.] is in supercell
